services:
  nginx:
    image: nginx:stable
    volumes:
      - ./www:/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /dev/shm/:/dev/shm/
      - /watorvapor/ecdsa-cert/certbot/etc:/etc/cert
      - /watorvapor/log/nginx:/log
    network_mode : "host"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
