version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./www:/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /watorvapor/ecdsa-cert/certbot/etc:/etc/cert
      - /watorvapor/log/nginx:/log
      - /dev/shm/:/dev/shm/
    network_mode : "host"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
  api:
    image: node:lts
    volumes:
      - ./wss:/wss
      - /dev/shm/:/dev/shm/
    working_dir: "/wss"
    command: node ./index.js
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
