version: '3'
services:
  nginx:
    image: nginx:stable
    user: $UID:$GID
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../www:/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /watorvapor/cert:/etc/cert
      - /watorvapor/log/nginx:/log
      - /tmp/wator/:/tmp/wator/
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
  wss:
    image: node:lts
    user: $UID:$GID
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../wss:/opt/wss
      - /tmp/wator/:/tmp/wator/
    working_dir: "/opt/wss"
    command: node ./index.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
